//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressForm.MvcWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddressFormResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddressFormResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddressForm.MvcWeb.Resources.AddressFormResources", typeof(AddressFormResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Address.
        /// </summary>
        public static string ExtendedAddressLabel {
            get {
                return ResourceManager.GetString("ExtendedAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string LocalityLabelCA {
            get {
                return ResourceManager.GetString("LocalityLabelCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City / Town.
        /// </summary>
        public static string LocalityLabelOther {
            get {
                return ResourceManager.GetString("LocalityLabelOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string LocalityLabelUS {
            get {
                return ResourceManager.GetString("LocalityLabelUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City field is required..
        /// </summary>
        public static string LocalityRequiredErrorMessageCA {
            get {
                return ResourceManager.GetString("LocalityRequiredErrorMessageCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City / Town field is required..
        /// </summary>
        public static string LocalityRequiredErrorMessageOther {
            get {
                return ResourceManager.GetString("LocalityRequiredErrorMessageOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City field is required..
        /// </summary>
        public static string LocalityRequiredErrorMessageUS {
            get {
                return ResourceManager.GetString("LocalityRequiredErrorMessageUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCodeLabelCA {
            get {
                return ResourceManager.GetString("PostalCodeLabelCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP / Postal Code.
        /// </summary>
        public static string PostalCodeLabelOther {
            get {
                return ResourceManager.GetString("PostalCodeLabelOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Code.
        /// </summary>
        public static string PostalCodeLabelUS {
            get {
                return ResourceManager.GetString("PostalCodeLabelUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Postal Code field is required..
        /// </summary>
        public static string PostalCodeRequiredErrorMessageCA {
            get {
                return ResourceManager.GetString("PostalCodeRequiredErrorMessageCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ZIP Code field is required..
        /// </summary>
        public static string PostalCodeRequiredErrorMessageUS {
            get {
                return ResourceManager.GetString("PostalCodeRequiredErrorMessageUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string RegionLabelCA {
            get {
                return ResourceManager.GetString("RegionLabelCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State / Province / Region.
        /// </summary>
        public static string RegionLabelOther {
            get {
                return ResourceManager.GetString("RegionLabelOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string RegionLabelUS {
            get {
                return ResourceManager.GetString("RegionLabelUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Province field is required..
        /// </summary>
        public static string RegionRequiredErrorMessageCA {
            get {
                return ResourceManager.GetString("RegionRequiredErrorMessageCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The State field is required..
        /// </summary>
        public static string RegionRequiredErrorMessageUS {
            get {
                return ResourceManager.GetString("RegionRequiredErrorMessageUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string StreetAddressLabel {
            get {
                return ResourceManager.GetString("StreetAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SubmitButtonLabelEdit {
            get {
                return ResourceManager.GetString("SubmitButtonLabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Person.
        /// </summary>
        public static string SubmitButtonLabelNew {
            get {
                return ResourceManager.GetString("SubmitButtonLabelNew", resourceCulture);
            }
        }
    }
}
